### ISSUE TITLE
precision loss in datum transform

### ISSUE THREAD

**Issue by fuzhenn** [MapTalks/proj4m#1]
现在datum转换都采用先转换为wgs84 datum, 再由wgs84转为目标datum的方式

但这个方式是有精度损失的, 主要是gcj02和wgs84互转时精度无法保证.

这个问题在yum中造成绘制和保存时会发生一些偏差.

故gcj02, bd09和wgs84三种坐标互转时, 需要直接转化,不能用wgs84作为中介, 而要用gcj02作为中介

**Comment by FuZhenn** [comment]
https://github.com/duscin/yumgis2/issues/95
