### ISSUE TITLE
缺少identity的CRS定义

### ISSUE THREAD

**Issue by fuzhenn** [MapTalks/proj4m#2]
这么定义吗?
"+proj=identity +datum=+no_defs"

**Comment by wsw0108** [comment]
这个没必要和projection严格一一对应吧

**Comment by fuzhenn** [comment]
我们需要支持平面坐标, 我把平面坐标的crs也取名叫identity了, 以后遇到这个crs就知道图形是个平面坐标图形
但identity crs缺少一个proj4的定义

**Comment by wsw0108** [comment]
支持平面坐标是一回事，proj4做投影坐标系转换又是另一回事了。
我觉得两者不适合混在一起。

**Comment by fuzhenn** [comment]
你的意思是不需要做proj4投影转换的crs就不要用proj形式定义?
那平面坐标你觉得怎么定义这个crs比较好?
