### ISSUE TITLE
增加新的接口, 减少数据转换

### ISSUE THREAD

**Issue by wsw0108** [MapTalks/proj4m#9]
通过定义接口, 来兼容其他类Point类型.
参考:
- https://github.com/hgoebl/simplify-java/blob/master/src/main/java/com/goebl/simplify/Point.java
- https://github.com/hgoebl/simplify-java/blob/master/src/main/java/com/goebl/simplify/PointExtractor.java

**Comment by wsw0108** [comment]
https://github.com/wsw0108/benchmarks/blob/master/src/main/java/org/maptalks/benchmark/proj4/Proj4mBenchmark.java
未见(明显)性能提升

**Comment by fuzhenn** [comment]
性能虽然没提升，但避免了不少double[]的创建，应能改善GC，感觉值得修改

**Comment by wsw0108** [comment]
@fuzhenn 虽然避免了double[]的创建, 但交换条件是forward/inverse只能修改传入的Point类对象. 在泛型里, 根据Java规范, 是没法如下的:
```java
public class Klass<T> {
  public T newInstance() {
    return new T; // error
  }
}
```
